SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS login_Reg_DB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE login_Reg_DB;


CREATE TABLE IF NOT EXISTS users (
    user_id		INT						NOT NULL		AUTO_INCREMENT	PRIMARY KEY,
    user_uniq	VARCHAR(255)	NULL,
    first_name	VARCHAR(100)	NOT NULL,
    last_name	VARCHAR(100)	NOT NULL,
    email			VARCHAR(255)	NOT NULL,
    passcode		VARCHAR(255)	NOT NULL,
    birth_date	VARCHAR(10)	NULL,
    created_at	DATETIME			NULL,
    updated_at	DATETIME			NULL
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
